# Generated by Django 5.2 on 2025-04-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
