<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-27 16:00
=======
# Generated by Django 5.2 on 2025-04-27 09:02
>>>>>>> f2f71b380a2bc4864356c396c692415d4babf7c3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('ticket_type', models.CharField(choices=[('day_pass', 'Day Pass'), ('session', 'Session')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used', models.BooleanField(default=False)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
        ),
    ]
